### ISSUE TITLE
Please Add Support for Conveyor Floor Holes

### ISSUE THREAD

**Issue by Nykademos** [SmartFoundations/SmartIssueTracker#10]
I want Extend to copy my lifts and conveyor holes as placed.  Lifts alone is helpful, but I also regularly build under feeding systems that use a lot of floor holes, I don't expect the layer below to be modified, however, adding the extend feature to splitters as if they were machines would help complete that operation in a separate step. (or maybe treat the floor holes like machines)

**Comment by majormer** [comment]
This may need to be split between lift support and conveyor hole support.  The latter it seems may require a Coffee Stain update to support.  However, lifts are being evaluated.

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/11

Please follow up there.
