### ISSUE TITLE
Adding support for basic wall 1M

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#11]
Most of the wall types are already implemented in the extend feature but sadly not the 1M variant of the basic wall.
This can be especially handy when doing lots of "shutters" for decoration, since we have spacing thanks to Smart!
Would love to have that added.
Thanks for the amazing and hard work Alex!

**Comment by ShadedPL** [comment]
![image](https://user-images.githubusercontent.com/4216212/184474978-1f8925a2-7503-45fa-8ae4-674b980d5a3a.png)
support for the FICSIT Wall version is there, horray!
Still missing the other materials (Concrete/Steel)
![image](https://user-images.githubusercontent.com/4216212/184475007-f5aa80a8-64e2-48f8-acbc-ebc39c3fec09.png)
![image](https://user-images.githubusercontent.com/4216212/184475012-421fe751-2e32-4beb-a62e-dc53771fcb74.png)

**Comment by SmartFoundations** [comment]
2d zoop on them works amazing

**Comment by ShadedPL** [comment]
All done, all variants are there, again super thanks!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/12

Please follow up there.
