### ISSUE TITLE
Open Source the Mod To Allow Others To Contribute

### ISSUE THREAD

**Issue by TheLargeCactus** [SmartFoundations/SmartIssueTracker#128]
**Is your feature request related to a problem? Please describe.**
Currently there are a good few issues with this mod, it's an awesome one but it could be even better! There are a lot of examples of projects soaring after taking their repo open source, and the benefits usually outweigh the costs in a lot of important aspects of the SDLC: https://www.heavybit.com/library/article/open-source-software-benefits-advantages

**Describe the solution you'd like**
Make the repo open source so that others can contribute to it's development.

**Describe alternatives you've considered**
A potential alternative to open source requires finding trustworthy people to allow access to the repo. This is usually more difficult when you don't have any examples of people working on this project though, and generally requires additional vetting that can be as time consuming to manage as the project itself.

**Additional context**
N/A

**Comment by majormer** [comment]
Thank you for your suggestion, @TheLargeCactus. We appreciate your interest in contributing to the Smart! Foundations mod. We have discussed the idea of open sourcing the mod many times in the past, and while we acknowledge the benefits of doing so, it is not something that we are considering at this time. Smart! Foundations is a project that Alex is very proud of, and he wishes to continue to "own" that body of work.

We don't deny that open sourcing the mod could potentially allow it to grow exponentially, and would very likely be very good for the mod in general. However, at this point, the decision to keep the mod closed source is purely personal. As a programmer myself and as the Community Manager of the mod, I can attest that the mod is extremely complicated and requires a significant amount of C++, Unreal Engine, and Satisfactory modding experience just to get started with the contribution process. Even with previous attempts to coach people up to the skills needed, it has proven to be non-productive, and has led to a significant investment of time with no real progress.

That said, we are always open to feedback from the community, and we may revisit the idea of open sourcing the mod in the future. If that happens, we will be sure to inform the community. We understand the benefits that open sourcing can bring to a project, and we are grateful for your input on this matter. Thank you again for your suggestion.

**Comment by TheLargeCactus** [comment]
Understood, and the reasoning you gave makes sense. Hopefully you won't get too many more people trying to ask this now that there exists a closed issue in your queue (I didn't find one when I looked initially but apologies if one already existed). I'll go ahead and close this issue with your above context in mind. Thanks for taking the time to answer!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/127

Please follow up there.
