### ISSUE TITLE
Toggleable camera and camera control

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#14]
The new camera system is amazing!! I would have two suggestions to make it even better:
1. have the camera toggleable, as it's not always needed and is taking up some screenspace, either via key or settings but key would be the best as sometimes you need it immediately.
2. have camera controls, as currently for foundations the camera is very zoomed in. A zoom in/out and rotate via shortcut+scroll would be amazing.

Thanks again for all the hard work Alex!

**Comment by ShadedPL** [comment]
as of 18.0.9 most of this is implemented, apart from the camera toggle, so I'll keep this open for now

**Comment by ShadedPL** [comment]
as of 19.2 camera toggle is here and working fine, closing this request. Thanks Alex!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/15

Please follow up there.
