### ISSUE TITLE
Black camera for buildings, conveyors and walls

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#15]
Currently all buildings, conveyor bels and walls have black cameras when extending.
Would be great if the camera could be off for the time being for the not yet implemented buildings

I'm sure you are aware of this bug but this is just to keep this one logged for others also to see, that it's a know bug.

![image](https://user-images.githubusercontent.com/4216212/180247386-c6008249-fd95-4faf-8f51-c6c591d367bb.png)

**Comment by Nykademos** [comment]
I also want this

**Comment by ShadedPL** [comment]
as far as I've tested all various buildings this is now fixed in 18.0.9

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/16

Please follow up there.
