### ISSUE TITLE
Display absolute height for foundations same as for lifts.

### ISSUE THREAD

**Issue by SmartFoundations** [SmartFoundations/SmartIssueTracker#24]
That will make it easier to align the factory later

**Comment by ShadedPL** [comment]
I had the same thought today, definitely agreed!

**Comment by majormer** [comment]
+1

**Comment by Nykademos** [comment]
+1

**Comment by majormer** [comment]
This is available in 18.0.9.  Closing.

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/24

Please follow up there.
