### ISSUE TITLE
Belt placement misaligned during extend, when close to other splitters

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#25]
As seen below, when extending, the belt connecting the mergers is misaligned, possibly to the proximity to the splitter:
![image](https://user-images.githubusercontent.com/4216212/180645258-4544a726-48de-4973-845a-f8d553c04932.png)

without the splitter it works fine:
![image](https://user-images.githubusercontent.com/4216212/180645339-50a8ae0a-ef4a-4f3d-b2d3-dc1d6e59a32d.png)

also the other way around it works for some reason:
![image](https://user-images.githubusercontent.com/4216212/180645280-9e796501-6bbb-446d-ad18-dd9343a01221.png)

**Comment by Nykademos** [comment]
+1

**Comment by ShadedPL** [comment]
this is fixed in 19.3, can't no longer reproduce this bug
![image](https://user-images.githubusercontent.com/4216212/184475393-dd61f8a2-4dec-4ebf-86ca-40bff3a1703f.png)

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/25

Please follow up there.
