### ISSUE TITLE
Can't go back to red axis after activating green axis

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#26]
Anytime I switch to the green axis when extending I can't go back to the red axis to make adjustments, which is extremely annoying when building huge things. I basically have to extend the red axis to the desired lenghts first and then make adjustments to the other axis, since I can't go back to the red one.

https://streamable.com/v4rco9
whenever you see a blue arrow is me pressing shift, expecting a red arrow again, but no success.

Currently running 18.0.9

**Comment by majormer** [comment]
Issue found and resolved in testing.  Should be resolved in next build.

**Comment by ShadedPL** [comment]
yep, I can confirm, this is fixed now.

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/26

Please follow up there.
