### ISSUE TITLE
Client FPS with Camera

### ISSUE THREAD

**Issue by sucr4m** [SmartFoundations/SmartIssueTracker#29]
**Describe the bug**
While building with camera, other clients FPS are heavily affected.

**To Reproduce**
Example: Somebody builds goes into build mode, no issue yet, as soon as Smart is triggered and the camera pops up everybody else thats a client (cant confirm if me as the host is affected because my pc is times more powerfull than the ones of my clients) FPS go down to single didgets, if not freezing the game. FPS recover after the one thats building leaves build mode.

**Screenshot of the mod's configuration**
Default.

**Screenshots/videos**
not really screenshotteble.

**(please complete the following information):**
 - Experimental
 - Epic host - Clients mixed.
 - CL195135
 - Public i guess?
 - 18.0.9

**Additional context**
The weird thing is that the ones that are not seeing the camera window are affected. Since this is not useble at all for us, we reverted back to 18.0.7. My clients arent really into bug hunting :<

**Comment by luxx** [comment]
I am also experiencing significant framerate drop during build mode in single player.

Looks like only smart-enabled buildings lag. For example, basic 1m wall does not lag, but 4m wall does. Vehicles, craft bench, hypertubes have no lag. Foundations, factory buildings, belts, pipes, stackable conveyor poles all lag.

Looking down at foundation, fps at 64 / 15ms, open build mode, 30 fps / 32ms.

Let me know if any other details would help.

**Comment by ShadedPL** [comment]
can you please check again in the newest version (18.14)? This should be fixed now :)

**Comment by SmartFoundations** [comment]
This was fixed a long time ago. If the issues continue and FPS are bad for you - please reopen this and describe the problem.
Be sure to use the latest test version V19.5 from SMM

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/29

Please follow up there.
