### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by yaitsbilly** [SmartFoundations/SmartIssueTracker#31]
When using Smart to place foundations, I've been crashing. Not all the time but at random times.

https://pastebin.com/raw/xUV1pWMZ

 - Game Branch: U5
 - Game Type Steam
 - Game Version CL188609
 - Mod Type Public
 - Mod Version 18.0.0
 - SMM/SML Version 3.3.1

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/31

Please follow up there.
