### ISSUE TITLE
Please remake axis keys to single button toggle

### ISSUE THREAD

**Issue by Nykademos** [SmartFoundations/SmartIssueTracker#35]
Axis choice is currently controlled by three separate keys CTRL, SHIFT, and ALT, I feel like this could be simplified to one button as a toggled option

I would like ALT to be the prime key to toggle axis

This mod uses a lot of buttons and as time goes on and features are added not only to the mod but also to the game, It's becoming difficult to find ways to rebind functions to usable keys.

**Comment by ShadedPL** [comment]
Love the idea! Especially, since this could fix #26

**Comment by SmartFoundations** [comment]
@ShadedPL @Nykademos  hmm. but to get from Y to X I will need to press this button once and then press it the second time and hold it. if I release it then I will need to "go around" again?

**Comment by Nykademos** [comment]
> @ShadedPL @Nykademos hmm. but to get from Y to X I will need to press this button once and then press it the second time and hold it. if I release it then I will need to "go around" again?

No...to go from y to x, press key, to go from x to z, pres key... this suggestion isn't intended to use any "hold" of the key, just press key=change axis.

**Comment by SmartFoundations** [comment]
example: I pressed Z for building in Z direction. 
but I want to scroll. if I press Z again then I get back to X but how do I rotate the building then?

> > @ShadedPL @Nykademos hmm. but to get from Y to X I will need to press this button once and then press it the second time and hold it. if I release it then I will need to "go around" again?
> 
> No...to go from y to x, press key, to go from x to z, pres key... this suggestion isn't intended to use any "hold" of the key, just press key=change axis. This would solve the issue of needing to press and hold multiple keys and in turn make the mod use less keys altogether

**Comment by Nykademos** [comment]
> example: I pressed Z for building in Z direction. but I want to scroll. if I press Z again then I get back to X but how do I rotate the building then?
> 
> > > @ShadedPL @Nykademos hmm. but to get from Y to X I will need to press this button once and then press it the second time and hold it. if I release it then I will need to "go around" again?
> > 
> > 
> > No...to go from y to x, press key, to go from x to z, pres key... this suggestion isn't intended to use any "hold" of the key, just press key=change axis. This would solve the issue of needing to press and hold multiple keys and in turn make the mod use less keys altogether

Buildings rotation should have been decided before...how often do you begin mass building and only after decide to rotate, with multiple buildings already showing?

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/35

Please follow up there.
