### ISSUE TITLE
Crash while choosing a walkway from the build menu (Crash report for 18.0.10)

### ISSUE THREAD

**Issue by Nykademos** [SmartFoundations/SmartIssueTracker#41]
![Version 18 0 10 crash report](https://user-images.githubusercontent.com/109456153/182739739-d684d8dc-270b-4221-88b3-58fb8925a550.PNG)

**Comment by SmartFoundations** [comment]
Please check this in the latest version of V19

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/40

Please follow up there.
