### ISSUE TITLE
Extending Coal Generator results in 5x belts (each connection) and 5x splitters on the new building

### ISSUE THREAD

**Issue by TheKrush** [SmartFoundations/SmartIssueTracker#42]
**Describe the bug**
Extending a Coal Generator results in the belts/splitter being duplicated (5x of everything, and costs 5x as well)

**To Reproduce**
1. Make a Coal Generator
2. Make a Splitter
3. Connect Splitter to Coal Generator
4. Extend the Coal Generator
5. Now dismantle the new stuff and notice there is 5x of everything (not the Coal Generator though)

**Screenshot of the mod's configuration**
![image](https://user-images.githubusercontent.com/671500/182773514-a0e6d9f1-2295-4b7f-81ad-a7d01d01bb89.png)

**Screenshots/videos**
https://www.youtube.com/watch?v=p4yD2xOI6q4

**(please complete the following information):**
 - Game Branch: Experimental
 - Game Type: Steam
 - Game Version CL195135
 - Mod Type: Public
 - Mod Version: 18.0.9
 - SMM/SML Version: 3.3.2
 - Is this in multiplayer (non-private session)? No
 - What other mods are you using? None.

**Additional context**
None.

**Comment by majormer** [comment]
I was able to reproduce this issue.  Seems isolated to coal generators, but might also impact other untested structures... I am not able to find another structure that is impacted in my testing.

**Comment by ShadedPL** [comment]
Yeah, I can totally reproduce this bug:
https://streamable.com/ue0xsp

**Comment by ShadedPL** [comment]
This is no longer valid in 19.3, please test and close, once confirmed :)

**Comment by SmartFoundations** [comment]
This is done and fixed in V19 test version. It can be now downloaded from SMM by manually selecting the version.
@TheKrush  If this continues - please reopen the issue

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/41

Please follow up there.
