### ISSUE TITLE
Can't stack Storage Containers 

### ISSUE THREAD

**Issue by Aunchi1** [SmartFoundations/SmartIssueTracker#45]
**Describe the bug**
Stacking of Vanilla Containers is impossible

**To Reproduce**
1. Go to the build menu
2. Select storage container
3. Try to stack them on top of each other

 - Game Branch: Experimental
 - Game Type Epic Games
 - Game Version CL#195135
 - Mod Type Public
 - Mod Version 18.13.58
 - SMM/SML Version 3.3.2
 - Multiplayer
 - Special Containers, Flex Splines, Remote Factory, Wall Pipe Supports, Huge Inventory, Passive Mode

**Additional context**
Might happen that containers are getting placed into each other

**Comment by majormer** [comment]
Double-tapping left shift should allow you to build a stacked storage container. Tapping left shift will disable the extend feature.

**Comment by ShadedPL** [comment]
yeah, like majormer said, disable Smart! by double pressing Shift and it will work just fine. This is not a bug :)

**Comment by SmartFoundations** [comment]
You can double tap Shift and it will be fine.
Or check the latest version 19.5 b431 test  from SMM

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/44

Please follow up there.
