### ISSUE TITLE
Add Link of Github to the Ficsit.app Mod Description

### ISSUE THREAD

**Issue by Mister-HACB** [SmartFoundations/SmartIssueTracker#47]
I would suggest adding the GitHub Link to the Mod description on https://ficsit.app/mod/SmartFoundations.

To get to this GitHub Page, you need to visit https://ficsit.app/mod/SmartFoundations (where you most likely got the Mod) → find the Discord Channel → Find the GitHub Link inside.

It would make it a lot easier to submit bug reports.

**Comment by majormer** [comment]
Thank you for filing this feature request.  Alex and I discussed this some, and while we see the benefit, we would prefer the Discord to be a sort of buffer to direct bug reporting.  That way, you will either need to have discussed with a mod the issue, or you would have been exposed to the chat bot which will direct you to other resources that may also solve the issue.

Further, when submitting a bug report, it often will be a day or two before it is seen and reviewed.  As a result, we lose the ability to do real time troubleshooting or collect additional information, which can be crucial to solving the issue.  Trying to follow up for more details after a person has left Discord or stops following the issue thread can be problematic, and leaves just closing the issue or leaving zombie issues open with no chance of solving, which doesn't help anyone.

In light of all of this, I am going to decline this feature request.  Please keep the ideas coming!  This was certainly worth reviewing!  Cheers!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/46

Please follow up there.
