### ISSUE TITLE
Coated foundations 2M missing Smart! functionality

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#50]
As in the title the 2M variant of Coated foundations does not have Smart! functionality.
All other heights and material variants work just fine.

**Comment by SmartFoundations** [comment]
because they had to name this one Build_Foundation_ConcretePolished_8x2_2  while everything else was just 8x1 8x2 8x4

**Comment by ShadedPL** [comment]
Yep, all working fine, closing this ticket
![image](https://user-images.githubusercontent.com/4216212/184474714-81a00cf3-8baa-4003-9c7e-ccb18e8d3870.png)

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/49

Please follow up there.
