### ISSUE TITLE
Crash when placing eyedropped machine / after extended visualisation

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#53]
When eyedropping a machine with belts and then placing it somewhere else crashes the game. I even managed to record it:
https://streamable.com/skooob

This actually also happens when taking the machine from the build menu but placing it next to another machine just to visualise the extend, like so:
https://streamable.com/ydrssh

However! When placing the machine without visualising the extend first it works just fine, also when eyedropping after that:
https://streamable.com/huqeff

Note: all the crashes are happening right after starting the game.

Currently running V 19.2 b222

Below the crash message:
https://gist.github.com/ShadedPL/68e473f6cec0a3c7e238a855cf52c471

**Comment by ShadedPL** [comment]
Couple of screenshots of the connections to the machine:
![image](https://user-images.githubusercontent.com/4216212/184087065-96551134-3afc-4bcd-aaca-a345032160ac.png)
![image](https://user-images.githubusercontent.com/4216212/184087157-f769a26d-9a3d-4d41-b087-41f4cc6b248c.png)

**Comment by ShadedPL** [comment]
Can't reproduce this bug anymore in 19.3, hence closing the issue

**Comment by ShadedPL** [comment]
Actually I just had another crash, please see below:
https://gist.github.com/ShadedPL/a4b0710747f6acc3e4a299b7c1531963

**Comment by SmartFoundations** [comment]
@ShadedPL  I heard that there is a way to do a recording of the recent activity from Nvidia control panel https://www.youtube.com/watch?v=sHewKlcOkzA

I added another condition to a line that was crashing for you so in the next version if you'll see the crash - it will be from something else.

**Comment by ShadedPL** [comment]
Can't reproduce this anymore in any way, should it happen again I'll reopen.
Thanks!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/52

Please follow up there.
