### ISSUE TITLE
Coal generators autoconnect to mergers

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#54]
As seen in the picture, Coal generators autoconnect to mergers, resulting in a impossible connection:
![image](https://user-images.githubusercontent.com/4216212/184077457-1bef78d8-0696-4e37-921f-5b456b5be4e5.png)

**Comment by ShadedPL** [comment]
All fixed now in 19.3
![image](https://user-images.githubusercontent.com/4216212/184475063-9134699d-c53c-416d-8858-80a391a89419.png)

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/53

Please follow up there.
