### ISSUE TITLE
Conveyor elevators, belts and distributors removed with each placed machine during extend

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#55]
With each placed manufacturer the connections get scrambled which could be the reason that the elevators get removed, had to make a video with voice to make this one more clear as I'm unable to explain it here:
https://streamable.com/jt974k
PS. in the video I say "mergers" but mean of course splitters

**Comment by ShadedPL** [comment]
I've made a different scenario with lifts going up, same results:
https://streamable.com/kuixab

**Comment by ShadedPL** [comment]
![image](https://user-images.githubusercontent.com/4216212/184175101-85f332ac-5c49-4472-abb4-79dd235275eb.png)
same thing happening to other machines

**Comment by SmartFoundations** [comment]
`PS. in the video I say "mergers" but mean of course splitters`

In code I call them all distributors or distribs.

**Comment by ShadedPL** [comment]
![image](https://user-images.githubusercontent.com/4216212/184325748-4fd7a2c6-4c08-43c8-ba95-936e6f62a2de.png)
so it's not just elevators as it turns out.. but everything :D

**Comment by Xdoras** [comment]
https://streamable.com/a6lypc
Mergers not connecting when using extend and unable to manually connect. Sometimes, the input/output won't get extended at all, or just one of the two will.

**Comment by ShadedPL** [comment]
All seems to be working fine again in 19.3, hence closing

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/54

Please follow up there.
