### ISSUE TITLE
Crash during autoconnect with manufacturers

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#56]
The second that autoconnect is trying to connect splitters to manufacturers the game is crashing
What I was doing:
https://streamable.com/u6ftw6

Also this was freshly after a game-start if it makes any difference.

And here the crash-report:
https://gist.github.com/ShadedPL/9b699120d26cabbda1d44ed7b8b765ac

**Comment by ShadedPL** [comment]
since this is apparently fixed and thus my best efforts I can no longer reproduce this bug, hence closing

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/55

Please follow up there.
