### ISSUE TITLE
Autoconnect with Assemblers (or in general) is not working properly

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#58]
As seen in the video
https://streamable.com/1iw4xo

Something is not right with the autoconnect for Assemblers, the splitters get stacked but I think it should be by default the "stair" setup as before.
![image](https://user-images.githubusercontent.com/4216212/184475999-8039bc32-680a-4f67-93b4-d26ef048e5ac.png)
Same thing happening with Blenders
![image](https://user-images.githubusercontent.com/4216212/184475960-df1e3f78-e129-4ac5-a947-e82ba1be1d13.png)

With other machines like Manufacturers, Foundries this is working fine.

**Comment by ShadedPL** [comment]
Scratch the idea that it's working fine with manufacturers, while the visualization is ok:
![image](https://user-images.githubusercontent.com/4216212/184476123-f19608d3-4df9-4ea2-900e-1285326d30b9.png)
the end result is not:
![image](https://user-images.githubusercontent.com/4216212/184476142-647c9d61-fe95-44a8-99a4-cc47181e650c.png)

**Comment by ShadedPL** [comment]
Same thing could be happening to pipes I believe:
![image](https://user-images.githubusercontent.com/4216212/184476266-8952eb0a-f26a-4403-98b1-6c51873ee34d.png)

**Comment by SmartFoundations** [comment]
This happens only when the input is from North side of the map and Splitter is oriented to the East side.
Let's multiply this by a dozen conditions and the head can blow up.
But I think I found the reason

**Comment by SmartFoundations** [comment]
![Скриншот 13-08-2022 17 43 28](https://user-images.githubusercontent.com/109308431/184480190-0b4efd91-deac-460c-aed7-45dbc9d5e108.jpg)

**Comment by ShadedPL** [comment]
![image](https://user-images.githubusercontent.com/4216212/184481801-56d9fd1a-468c-4d49-a617-b8f074856556.png)
yep, looks to be fixed in, although I still think that the previous, staired approach for splitters with assemblers looked better, but the belts are fine, plus we can always fix that with extend

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/57

Please follow up there.
