### ISSUE TITLE
MK2 Pipes the only option

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#65]
Right now MK2 pipes are the only option when doing Smart! operations, even not having unlocked MK2 pipes yet.
It should be similar to belts, that it chooses the pipe level automatically based on what is unlocked by the player.
Also players should be able to force the pipe level, just like belts, via the settings.

**Comment by ShadedPL** [comment]
This is actually already implemented, hence closing the ticket. Thanks!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/64

Please follow up there.
