### ISSUE TITLE
Build Mode functionality

### ISSUE THREAD

**Issue by Nykademos** [SmartFoundations/SmartIssueTracker#8]
Using the current Build Mode that incorporates zooping creates some loss of function.  Player has difficulty placing single foundations vertically without zoop creating horizontal foundations.  It also makes every build process two clicks, Build Mode  in Vanilla allows zooping to be turned off preventing this.

Separate Build Modes would be better. Smart being independent form all other vanilla Build Modes

Ability to Disable Zoop in The Smart! menu could also help

As Pipes and other Architecture (like Beams) are added to Smart! these build modes will be necessary to maintain base game functions 

Expanding on this request-  8/04/22  Giving splitters and mergers the ability to switch build modes from "Autoconnect" to "Default" would help users turn off auto-connect intuitively, rather than needing to learn the dbl SHIFT method that is not intuitive and most people don't know about.

**Comment by Jumbo-storm** [comment]
Would like this feature to be added too!:)

**Comment by webdestroya** [comment]
Yes, please bring back the old functionality. The need to double click for everything now is so tedious. Having the double foundations makes things even more steps to complete because I end up having to delete errant foundation blocks.

**Comment by ShadedPL** [comment]
Toggleable zoop is a must-have. Probably the best approach would be build modes single-zoop-Smart, 
Maybe have Zoop and vertical somehow combined? If not then an additional build mode would be needed and that's beginning to go into the wrong direction again..

**Comment by majormer** [comment]
Sounds like the requested solution is to make Zoop functionality in Smart! be optional due to the additional click needed to trigger a single click build.

**Comment by Nykademos** [comment]
Expanding on this request- 8/04/22 Giving splitters and mergers the ability to switch build modes from "Autoconnect" to "Default" would help users turn off auto-connect intuitively, rather than needing to learn the dbl SHIFT method that is not intuitive and most people don't know about. 
-put this in the comment section too so previous commenters can see it more easily

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/9

Please follow up there.
