### ISSUE TITLE
Common issues in Update 6 (Early Access branch)

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#93]
Here's a quick list of the known issues since the release of EA update 6, please add your comments here so the post can be updated.
**1. Placing a lot of foundations at once crashes game**
Crash log:
https://gist.github.com/ShadedPL/27298c0a32fd8aa400bef57303ae3c90

**2. Extend not working for pipes** 
for some it doesn't want to snap at all, for some it works but no fluid going through the "to building" pipes, more testing 
![image](https://user-images.githubusercontent.com/4216212/191366300-61baefb9-5b43-4bec-92a7-9ec5f83db6a9.png)
MK2 pipes seem to create the snapping issue
![image](https://user-images.githubusercontent.com/4216212/191367034-152cfd3a-cc58-4943-807c-0c1c8a7002be.png)

**3. Vertical spacing of foundations is incorrect**
no matter the size, the vertical distance between foundations is always 8M
![image](https://user-images.githubusercontent.com/4216212/191366608-f00f0226-f17a-4e2a-b31d-9484d75aa75d.png)
walls are fine

**Comment by Sprinkles-GS** [comment]
4. Dufault build mode missing for foundations
![image](https://user-images.githubusercontent.com/41163001/191797625-628faac9-967d-43da-afc8-f202abfaf4ac.png)

**Comment by majormer** [comment]
1, 2, and 3 should be fixed in Smart V20.  4 is not a bug, but instead was a rename of the build mode. We may look at clarifying that in the future.

**Comment by ShadedPL** [comment]
Can, confirm everything works fine in V20, closing this ticket. 
I just want to give my dearest appreciation to the whole Team that was responsible to deliver this much needed update, although dealing with multiple roadblocks. 
Can't thank you enough :)

**Comment by SmartFoundations** [comment]
@ShadedPL  You are very welcome!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/92

Please follow up there.
